name: 'Linode cli tools'
description: 'Make the Linode cli available to your workflow'
author: 'Sergey Shevchenko'
inputs:
  LINODE_CLI_TOKEN:
    description: 'linode cli token'
    required: true
branding:
  icon: 'terminal'
  color: 'green'
runs:
  using: 'node16'
  main: 'dist/index.js'
